 
           - name: "yum configration"
             yum_repository:

                    name: "kubernetes"
                    description: "kubernetes repo"
                    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                    enabled: yes
                    gpgcheck: yes
                    repo_gpgcheck: yes
                    gpgkey:
                             - https://packages.cloud.google.com/yum/doc/yum-key.gpg
                             - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

           - name: "Install plugins"
             package:
                      name: "{{ item }}"
                      state: present
             loop:  
                  - docker
                  - kubelet
                  - kubeadm
                  - iproute-tc
                  - kubectl   
                
           - name: "start services"
             service:
                      name: "{{ item }}"
                      state: started
                      enabled: yes
             loop:  
                  - docker
                  - kubelet 

           - name: "config image pull"
             command:  kubeadm config images pull 
                   
           - name: "docker c-group"
             copy:
                  dest: /etc/docker/daemon.json
                  content: '{
                         "exec-opts": ["native.cgroupdriver=systemd"]
                     }'
                     
           - name: "restart docker svc"
             service: 
                   name: "docker"
                   state: "restarted"
           
               
               
           - name: "ignore Error file content"
             copy:
                  dest: /etc/sysctl.d/k8s.conf
                  src: bridge.yml
          
           - name: "restart sysctl --system" 
             command: "sysctl --system"        
                   

           - name: "kubeadm init config & ignoreing errors & k8s inilization"
             shell: 
                    cmd: "{{ item }}"       
             loop:
                   - "kubeadm init --pod-network-cidr={{ cidr }}/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
                   - "sudo mkdir -p $HOME/.kube"
                   - "sudo cp -fi /etc/kubernetes/admin.conf $HOME/.kube/config"
                   - "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

           - name: "create Token"
             shell: "kubeadm token create  --print-join-command > ~/token.txt"

           - name: "Copying Token"
             fetch:
                    dest: "/token.txt"
                    src: "~/token.txt"
                    flat: yes

           - name: "flannel installation"
             command: "kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"               
          
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
       
