---
 - name: AWS ec2 instance
   ec2:
                    key_name: "{{ ssh_key }}"
                    instance_type: "{{ i_type }}"
                    image: "{{ ami }}"
                    wait: yes
                    region: "{{ region }}"
                    group_id: "{{ sg_groups }}"
                    count: "{{ count_ins }}"
                    instance_tags:
                            Name: "{{ tag_name }}"
                    vpc_subnet_id: "{{ subnet_id }}"
                    assign_public_ip: yes
                    aws_access_key: "{{ access_key }}"
                    aws_secret_key: "{{ secret_key }}"

   register: ec2
 - file:
             path: "/etc/ansible/inventory"
             state: file
 - lineinfile:
             path: "/etc/ansible/inventory"
             line: "[{{tag_name}}]"
 - lineinfile:
             dest: "/etc/ansible/inventory"
             regexp: '^[{{ tag_name  }}]'
             # line: "{{ item ['public_ip'] }} ansible_user=ec2-user ansible_ssh_private_key_file={{ ssh_key_full_path }}  ansible-connection=ssh"                  
             line: "{{ item ['public_ip'] }} ansible_user=ec2-user ansible_ssh_private_key_file={{ ssh_key }}  ansible-connection=ssh"
             
             
   loop: "{{ec2.instances}}"
             #    path: "~/inventory"
 - meta: refresh_inventory
# tasks file for awsrole
