 
           - name: "yum configration"
             yum_repository:

                    name: "kubernetes"
                    description: "kubernetes repo"
                    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                    enabled: yes
                    gpgcheck: yes
                    repo_gpgcheck: yes
                    gpgkey:
                             - https://packages.cloud.google.com/yum/doc/yum-key.gpg
                             - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

           - name: "Install plugins"
             package:
                      name: "{{ item }}"
                      state: present
             loop:  
                  - docker
                  - kubelet
                  - kubeadm
                  - iproute-tc
                  - kubectl   
                
           - name: "start services"
             service:
                      name: "{{ item }}"
                      state: started
                      enabled: yes
             loop:  
                  - docker
                  - kubelet 
                   
           - name: "docker c-group"
             copy:
                  dest: /etc/docker/daemon.json
                  content: '{
                         "exec-opts": ["native.cgroupdriver=systemd"]
                     }'
                     #notify:
                     #- Restart docker
           - name: "restart docker svc"
             service: 
                   name: "docker"
                   state: "restarted"
           
               
               
           - name: "--Bridge  file content"
             copy:
                  dest: /etc/sysctl.d/k8s.conf
                  src: bridge.yml
          
           - name: "restart sysctl --system" 
             command: "sysctl --system"        
                   

           - name: "Copying Token"
             copy:
                    src: "/token.txt"
                    dest: "~/token.txt"
           - name:  "Token Applied"
             shell:
                     cmd: "bash ~/token.txt "
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
       
